env:
  contexts:
    - name: JuiceShop
      urls:
        - http://127.0.0.1:3000
      excludePaths:
        - http://127.0.0.1:3000/socket.io/.*
      authentication:
        method: manual

  parameters:
    failOnError: false
    failOnWarning: false

jobs:

  - type: spider
    parameters:
      context: JuiceShop
      maxDuration: 10

  - type: passiveScan-config
    parameters:
      scanOnlyInScope: true

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: activeScan
    parameters:
      context: JuiceShop
      maxRuleDurationInMins: 2
      maxScanDurationInMins: 20

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/reports
      reportFile: zap-report.html

  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/reports
      reportFile: zap-report.json