name: DAST Scan

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        run: |
          npm ci

      - name: Install browsers
        run: |
          npx playwright install --with-deps

      #
      # Juice Shop 起動
      #
      - name: Start Juice Shop
        run: |
          docker run -d \
            --name juice-shop \
            -p 3000:3000 \
            bkimminich/juice-shop

      - name: Wait Juice Shop
        run: |
          timeout 120 bash -c \
          'until curl -s http://localhost:3000 > /dev/null; do sleep 5; done'

      #
      # ZAP 起動
      #
      - name: Start ZAP
        run: |
          docker run -d \
            --name zap \
            -u zap \
            -p 8080:8080 \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -daemon \
            -host 0.0.0.0 \
            -port 8080 \
            -config api.disablekey=true

      - name: Wait ZAP
        run: sleep 30

      #
      # Playwright
      #
      - name: Execute Playwright
        run: |
          npx playwright test

      #
      # Automation Framework
      #
      - name: Execute ZAP Automation Framework
        run: |
          mkdir reports

          docker cp \
            zap/automation.yaml \
            zap:/tmp/automation.yaml

          docker exec zap \
            mkdir -p /zap/reports

          docker exec zap \
            zap.sh \
            -cmd \
            -autorun /tmp/automation.yaml

          docker cp \
            zap:/zap/reports/. \
            reports

      - name: Show ZAP logs
        if: always()
        run: |
          docker logs zap

      - name: List reports
        if: always()
        run: |
          docker exec zap ls -R /zap

      #
      # レポート保存
      #
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports